export const browserCoreExamples = [
  "bot browser status",
  "bot browser start",
  "bot browser stop",
  "bot browser tabs",
  "bot browser open https://example.com",
  "bot browser focus abcd1234",
  "bot browser close abcd1234",
  "bot browser screenshot",
  "bot browser screenshot --full-page",
  "bot browser screenshot --ref 12",
  "bot browser snapshot",
  "bot browser snapshot --format aria --limit 200",
  "bot browser snapshot --efficient",
  "bot browser snapshot --labels",
];

export const browserActionExamples = [
  "bot browser navigate https://example.com",
  "bot browser resize 1280 720",
  "bot browser click 12 --double",
  'bot browser type 23 "hello" --submit',
  "bot browser press Enter",
  "bot browser hover 44",
  "bot browser drag 10 11",
  "bot browser select 9 OptionA OptionB",
  "bot browser upload /tmp/bot/uploads/file.pdf",
  'bot browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "bot browser dialog --accept",
  'bot browser wait --text "Done"',
  "bot browser evaluate --fn '(el) => el.textContent' --ref 7",
  "bot browser console --level error",
  "bot browser pdf",
];
